ingress:
  hostname: novostoic.proxy.localhost
  tls: false
  annotations: {}

controller:
  image: moleculemaker/novostoic-frontend

config:
  hostname: "https://mmli.fastapi.staging.mmli1.ncsa.illinois.edu"
  basePath: ""
  signInUrl: "https://mmli1.ncsa.illinois.edu/oauth2/start?rd=https%3A%2F%2Fnovostoic.proxy.localhost%2Fconfiguration"
  signOutUrl: "https://mmli1.ncsa.illinois.edu/oauth2/sign_out?rd=https%3A%2F%2Fnovostoic.proxy.localhost%2Fconfiguration"
  userInfoUrl: "https://mmli1.ncsa.illinois.edu/oauth2/userinfo"
extraDeploy: []
