/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobType = 'clean' | 'chemscraper' | 'molli' | 'novostoic_optstoic' | 'novostoic_novostoic' | 'novostoic_enzrank' | 'novostoic_dgpredictor';

export const JobType = {
    Clean: 'clean' as JobType,
    Chemscraper: 'chemscraper' as JobType,
    Molli: 'molli' as JobType,
    NovostoicOptstoic: 'novostoic_optstoic' as JobType,
    NovostoicNovostoic: 'novostoic_novostoic' as JobType,
    NovostoicEnzrank: 'novostoic_enzrank' as JobType,
    NovostoicDgpredictor: 'novostoic_dgpredictor' as JobType
};

